"""Process deploying conditional diffusion models on grid fields.

CorrDiff-style downscaling in a Kratos solution loop: per execution, the
configured input fields of the condition model part are sampled onto a
regular grid, an ensemble of fields is generated by reverse diffusion
(diffusion_utils.GenerateEnsemble), and the ensemble MEAN is scattered onto
the output fields - with the ensemble STANDARD DEVIATION optionally written
to "uncertainty_fields", giving every prediction a physics-ML uncertainty
band for free.

The documented variations (TopoDiff-style generative design, flow
reconstruction from sparse observations) reuse this process unchanged: only
the meaning of the condition channels differs.

Denoisers with 2D spatial layout (SongUNet-based preconditioners) consume
planar Kratos cases through the thin-axis idiom: "squeeze_axis" collapses
the thin grid axis before sampling and duplicates predictions across it on
the way back. Volumetric denoisers ("denoiser_interface": "unet3d",
physicsnemo.experimental.models.diffusion_unets.DiffusionUNet3D) consume
the full (C, D, H, W) grid instead - squeeze_axis stays off, and each grid
extent must be a power of 2 or a multiple of 2**(num_levels - 1).

torch/physicsnemo are imported lazily on first execution.
"""

import numpy

import KratosMultiphysics as Kratos
from KratosMultiphysics.PhysicsNeMoApplication.training import diffusion_utils
from KratosMultiphysics.PhysicsNeMoApplication.bridges import grid_bridge
from KratosMultiphysics.PhysicsNeMoApplication.deployment import model_registry
from KratosMultiphysics.PhysicsNeMoApplication.deployment import ood_guard_utils
from KratosMultiphysics.PhysicsNeMoApplication.bridges import torch_bridge
_EXECUTION_POINTS = ("initialize_solution_step", "finalize_solution_step")


def Factory(settings: Kratos.Parameters, model: Kratos.Model) -> "DiffusionInferenceProcess":
    if not isinstance(settings, Kratos.Parameters):
        raise TypeError("Expected input shall be a Parameters object, encapsulating a json string")
    return DiffusionInferenceProcess(model, settings["Parameters"])


class DiffusionInferenceProcess(Kratos.Process):
    """Generates a conditional diffusion ensemble every output_interval steps."""

    def __init__(self, model: Kratos.Model, settings: Kratos.Parameters) -> None:
        super().__init__()

        # optional OOD guard on the conditioning grid (see ood_guard_utils)
        ood_settings = Kratos.Parameters("{}")
        if settings.Has("ood_guard"):
            ood_settings = settings["ood_guard"].Clone()
            settings.RemoveValue("ood_guard")
        self._ood_guard = ood_guard_utils.GuardCheck(ood_settings)

        # optional CorrDiff regression stage (model_settings-shaped block):
        # its mean is added to the generated ensemble before mean/std - the
        # denoiser then models the RESIDUAL (see diffusion_utils)
        self.regression_settings = None
        if settings.Has("regression_settings"):
            self.regression_settings = settings["regression_settings"].Clone()
            settings.RemoveValue("regression_settings")

        default_settings = Kratos.Parameters("""{
            "model_part_name"        : "PLEASE_SPECIFY_MODEL_PART_NAME",
            "output_model_part_name" : "",
            "model_settings"         : {},
            "input_fields"           : [
                {
                    "variable_name" : "PLEASE_SPECIFY_VARIABLE_NAME",
                    "data_location" : "node_historical"
                }
            ],
            "output_fields"          : [
                {
                    "variable_name" : "PLEASE_SPECIFY_VARIABLE_NAME",
                    "data_location" : "node_historical"
                }
            ],
            "uncertainty_fields"     : [],
            "grid_shape"             : [8, 8, 2],
            "bounding_box"           : [],
            "squeeze_axis"           : -1,
            "denoiser_interface"     : "edm",
            "sampler_settings"       : {},
            "execution_point"        : "finalize_solution_step",
            "output_interval"        : 1
        }""")
        settings.ValidateAndAssignDefaults(default_settings)
        for key in ("input_fields", "output_fields", "uncertainty_fields"):
            for i in range(settings[key].size()):
                settings[key][i].ValidateAndAssignDefaults(default_settings["input_fields"][0])

        self.model_part = model[settings["model_part_name"].GetString()]
        output_part_name = settings["output_model_part_name"].GetString()
        self.output_model_part = model[output_part_name] if output_part_name else self.model_part
        self.model_settings = settings["model_settings"].Clone()
        self.sampler_settings = settings["sampler_settings"].Clone()
        self.denoiser_interface = settings["denoiser_interface"].GetString()
        if self.denoiser_interface not in ("edm", "dit", "unet3d"):
            raise ValueError(
                f"Unsupported denoiser interface \"{self.denoiser_interface}\". "
                "Use \"edm\" (net(x, img_lr, sigma) denoisers), \"dit\" "
                "(physicsnemo.models.dit.DiT) or \"unet3d\" (the volumetric "
                "physicsnemo.experimental.models.diffusion_unets.DiffusionUNet3D), "
                "the latter two wrapped via diffusion_utils.WrapDenoiser.")
        self.input_specs = self._ReadFieldSpecs(settings["input_fields"])
        self.output_specs = self._ReadFieldSpecs(settings["output_fields"])
        self.uncertainty_specs = self._ReadFieldSpecs(settings["uncertainty_fields"])

        self.grid_shape = tuple(int(n) for n in settings["grid_shape"].GetVector())
        if len(self.grid_shape) != 3:
            raise ValueError(f"\"grid_shape\" must have three entries, got {self.grid_shape}.")

        box = settings["bounding_box"].GetVector()
        if len(box) == 0:
            self.bounding_box = None  # resolved at first execution, then frozen
        elif len(box) == 6:
            self.bounding_box = (numpy.array(box[:3]), numpy.array(box[3:]))
        else:
            raise ValueError("\"bounding_box\" must be empty or [x0,y0,z0,x1,y1,z1].")

        squeeze_axis = settings["squeeze_axis"].GetInt()
        if squeeze_axis == -1:
            self.squeeze_axis = None
        elif squeeze_axis in (0, 1, 2):
            self.squeeze_axis = squeeze_axis
        else:
            raise ValueError(f"\"squeeze_axis\" must be -1 (off), 0, 1 or 2, got {squeeze_axis}.")
        if self.denoiser_interface == "unet3d" and self.squeeze_axis is not None:
            raise ValueError(
                "\"squeeze_axis\" cannot be combined with the volumetric \"unet3d\" "
                "denoiser interface: a squeezed (C, H, W) condition cannot feed a 3D "
                "U-Net. Leave squeeze_axis at -1, or use a 2D interface.")

        self.execution_point = settings["execution_point"].GetString()
        if self.execution_point not in _EXECUTION_POINTS:
            raise ValueError(
                f"Unsupported execution point \"{self.execution_point}\". "
                f"Supported: {', '.join(_EXECUTION_POINTS)}.")
        self.output_interval = settings["output_interval"].GetInt()
        if self.output_interval < 1:
            raise ValueError(f"\"output_interval\" must be >= 1 [ output_interval = {self.output_interval} ].")

        self._model = None
        self._device = None
        self._regression_model = None
        self._normalization = None
        self._input_normalization = None

    @staticmethod
    def _ReadFieldSpecs(fields: Kratos.Parameters):
        return [
            (fields[i]["variable_name"].GetString(), fields[i]["data_location"].GetString())
            for i in range(fields.size())
        ]

    def ExecuteInitializeSolutionStep(self) -> None:
        if self.execution_point == "initialize_solution_step":
            self._ExecuteIfDue()

    def ExecuteFinalizeSolutionStep(self) -> None:
        if self.execution_point == "finalize_solution_step":
            self._ExecuteIfDue()

    def _ExecuteIfDue(self) -> None:
        if self.model_part.ProcessInfo[Kratos.STEP] % self.output_interval == 0:
            self.RunDiffusion()

    def _Unsqueeze(self, grid):
        if self.squeeze_axis is None:
            return grid
        thin_size = self.grid_shape[self.squeeze_axis]
        return numpy.repeat(
            numpy.expand_dims(grid, 1 + self.squeeze_axis), thin_size, axis=1 + self.squeeze_axis)

    def RunDiffusion(self) -> None:
        if self._model is None:
            self._model, self._device = model_registry.LoadModelWithCardCheck(
                self.model_settings, self.input_specs, self.output_specs, type(self).__name__)
            if self.denoiser_interface in ("dit", "unet3d"):
                self._model = diffusion_utils.WrapDenoiser(self._model, self.denoiser_interface)
            # the denoiser's card carries the scaling of what the ensemble
            # emits (regression mean included, in the two-stage recipe)
            self._normalization = model_registry.LoadOutputNormalization(self.model_settings)
            self._input_normalization = model_registry.LoadInputNormalization(self.model_settings)
            if self.regression_settings is not None:
                self._regression_model, _ = model_registry.LoadModelWithCardCheck(
                    self.regression_settings, self.input_specs, self.output_specs,
                    type(self).__name__)

        if self.bounding_box is None:
            self.bounding_box = grid_bridge.ComputeBoundingBox(self.model_part)
        condition, _ = grid_bridge.SampleFieldsOnGrid(
            self.model_part, self.input_specs, self.grid_shape, self.bounding_box)
        if self.squeeze_axis is not None:
            condition = condition.mean(axis=1 + self.squeeze_axis)
        # the card's "input_normalization" on the condition, per channel
        # along axis 0 (the regression stage sees the same condition)
        condition = model_registry.ApplyInputNormalization(
            condition, self._input_normalization, channel_axis=0)

        if self._ood_guard.enabled:  # grid (C, *spatial) -> (prod(spatial), C) features
            torch = torch_bridge._TryImportTorch()
            self._ood_guard.Check(
                torch.from_numpy(condition.reshape(condition.shape[0], -1).T),
                type(self).__name__)

        ensemble = diffusion_utils.GenerateEnsemble(
            self._model, condition, self.sampler_settings.Clone())  # (S, C_out, *spatial)
        if self.regression_settings is not None:
            # CorrDiff inference: regression mean + residual ensemble - the
            # mean shifts, the ensemble spread stays the denoiser's
            ensemble = ensemble + diffusion_utils.RunRegressionMean(
                self._regression_model, condition,
                output_channels=ensemble.shape[1])[None]

        # the card's "output_normalization" makes the ensemble physical: the
        # mean is scaled AND shifted, the spread scaled only (a standard
        # deviation shifted by the training mean is meaningless)
        mean = model_registry.ApplyOutputNormalization(
            self._Unsqueeze(ensemble.mean(axis=0)), self._normalization, channel_axis=0)
        grid_bridge.ScatterGridToNodes(
            mean, self.bounding_box, self.output_model_part, self.output_specs)
        if self.uncertainty_specs:
            spread = model_registry.ApplyOutputNormalization(
                self._Unsqueeze(ensemble.std(axis=0)), self._normalization,
                scale_only=True, channel_axis=0)
            grid_bridge.ScatterGridToNodes(
                spread, self.bounding_box, self.output_model_part, self.uncertainty_specs)
